### ISSUE TITLE
Feature Request: Provide a library compatible with the Laravel FileSystem Storage

### ISSUE THREAD

**Issue by lalanikarim** [tray-labs/oracle-storage#10]
Would it be possible to provide library that is compatible with Laravel FileSystem Storage?
https://laravel.com/docs/5.7/filesystem

AWS Storage (S3), Google Cloud Storage, and Dropbox, etc provide LFS compatible implementation.

**Comment by barakaben** [comment]
Hi! Please help me solve this error which surfaces when I try to upload a file from my web app.

RuntimeException: SplFileObject::__construct(86a03f5ac14227ae4e596750c3a90db1612f77ce1b00e4aa6cbd4b2dc5e69835.icturee.jpg): failed to open stream: No such file or directory in /home/site/vendor/tray-labs/oracle-storage/src/Object/File.php:42 Stack trace: #0 /home/site/vendor/tray-labs/oracle-storage/src/Object/File.php(42): SplFileObject->__construct('86a03f5ac14227a...') #1 /home/site/vendor/tray-labs/oracle-storage/src/Service/UploadService.php(25): TrayLabs\OracleStorage\Object\File->getFile() #2 /home/site/vendor/tray-labs/oracle-storage/src/OracleStorage.php(64): TrayLabs\OracleStorage\Service\UploadService->handle('86a03f5ac14227a...', Object(TrayLabs\OracleStorage\Object\File)) #3 /home/site/includes/storageProcessor.php(15): TrayLabs\OracleStorage\OracleStorage->upload('86a03f5ac14227a...', Object(TrayLabs\OracleStorage\Object\File)) #4 /home/site/wwwroot/chumba.html(470): storeFile(Object(TrayLabs\OracleStorage\OracleStorage), '86a03f5ac14227a...', '86a03f5ac14227a...') #5 {main}
